const freezeEntry = (entry) => Object.freeze({
  maturity: "established",
  status: "source-backed",
  relations: [],
  failureModes: [],
  controls: [],
  ...entry,
  process: Object.freeze(entry.process ?? []),
  relations: Object.freeze(entry.relations ?? []),
  failureModes: Object.freeze(entry.failureModes ?? []),
  controls: Object.freeze(entry.controls ?? []),
});

export const AGENTIC_LAYERS = Object.freeze({
  agency: { label: "عامل و تصمیم", color: "#b9f227", icon: "◉" },
  harness: { label: "Harness و اجرا", color: "#62d9ce", icon: "⬡" },
  context: { label: "مهندسی Context", color: "#72a7ff", icon: "▤" },
  orchestration: { label: "Orchestration", color: "#f39a53", icon: "⌘" },
  protocol: { label: "پروتکل و تعامل", color: "#d6a6ff", icon: "⇄" },
  reliability: { label: "اعتمادپذیری و ایمنی", color: "#ff6b58", icon: "◇" },
  observability: { label: "مشاهده‌پذیری و ارزیابی", color: "#ffd166", icon: "⌁" },
});

export const AGENTIC_KIND_LABELS = Object.freeze({
  pattern: "الگوی طراحی",
  control: "کنترل مهندسی",
  protocol: "پروتکل",
  standard: "استاندارد / قرارداد",
  framework: "نمونهٔ فریم‌ورک",
  method: "روش",
});

export const AGENTIC_CATALOG = Object.freeze([
  freezeEntry({
    id: "agent-loop", layer: "agency", kind: "pattern", title: "حلقهٔ عامل", subtitle: "Observe → Decide → Act → Verify",
    summary: "عامل یک مدل تنها نیست؛ حلقه‌ای کنترل‌شده است که وضعیت را می‌بیند، اقدام ساختاری پیشنهاد می‌دهد، نتیجه را مشاهده می‌کند و با شرط پایان یا سقف بودجه متوقف می‌شود.",
    input: "هدف، وضعیت، سیاست و ابزارهای مجاز", output: "اقدام، مشاهده و نتیجهٔ نهایی",
    process: ["مشاهدهٔ وضعیت", "انتخاب گام", "اعتبارسنجی سیاست", "اقدام یا ابزار", "بازبینی و توقف"],
    source: "https://arxiv.org/abs/2210.03629", docs: "https://openai.github.io/openai-agents-python/running_agents/",
    failureModes: ["حلقهٔ بی‌پایان", "هدف مبهم", "اعتماد بیش از حد به مشاهده"], controls: ["maxSteps", "deadline", "terminal condition"],
  }),
  freezeEntry({
    id: "planner-executor", layer: "agency", kind: "pattern", title: "Planner / Executor", subtitle: "تفکیک طرح از اجرای گام",
    summary: "برنامه‌ریز کار را به گام‌های قابل سنجش می‌شکند و اجراگر فقط گام مجاز بعدی را انجام می‌دهد؛ طرح باید با مشاهده‌های تازه قابل بازنگری باشد.",
    input: "هدف و محدودیت‌ها", output: "طرح نسخه‌دار + نتایج گام‌ها",
    process: ["تجزیهٔ هدف", "ثبت وابستگی", "اجرای یک گام", "بررسی شاهد", "بازطرح در صورت تغییر"],
    source: "https://arxiv.org/abs/2305.04091", docs: "https://langchain-ai.github.io/langgraph/concepts/agentic_concepts/",
    relations: ["agent-loop", "workflow-dag"], failureModes: ["طرح شکننده", "توهم تکمیل"], controls: ["evidence gate", "re-plan trigger"],
  }),
  freezeEntry({
    id: "reflection-verifier", layer: "agency", kind: "method", title: "Reflection و Verifier", subtitle: "پاسخ دوم، شاهد اول را می‌سنجد",
    summary: "بازبین مستقل یا مرحلهٔ verifier خروجی را با معیار روشن، تست یا منبع می‌سنجد. تکرار فکر به‌تنهایی تضمین صحت نیست؛ معیار و شاهد لازم است.",
    input: "پاسخ نامزد + rubric + evidence", output: "قبول، رد یا بازخورد اصلاحی",
    process: ["ساخت نامزد", "اجرای معیار", "یافتن تعارض", "اصلاح محدود", "ثبت نتیجه"],
    source: "https://arxiv.org/abs/2303.11366", docs: "https://github.com/openai/evals",
    relations: ["agent-loop", "eval-gates"], failureModes: ["تأیید خطای مشترک", "rubric مبهم"], controls: ["independent evidence", "bounded revisions"],
  }),
  freezeEntry({
    id: "agent-harness", layer: "harness", kind: "pattern", title: "Agent Harness", subtitle: "پوستهٔ اجرای سیاست‌مند پیرامون مدل",
    summary: "Harness ورودی، مدل، state، ابزار، مجوز، بودجه، خطا و trace را به یک اجرای قابل کنترل تبدیل می‌کند. مدل پیشنهاد می‌دهد؛ Harness تصمیم اجرایی را اعمال می‌کند.",
    input: "run request + model adapter + policy", output: "event stream + state + terminal result",
    process: ["ایجاد Run", "مونتاژ Context", "فراخوانی مدل", "گیت اقدام", "ثبت رویداد و checkpoint"],
    source: "https://github.com/openai/openai-agents-python", docs: "https://openai.github.io/openai-agents-python/",
    relations: ["agent-loop", "tool-contract", "approval-gate", "trace-spans"], failureModes: ["اختلاط policy با prompt", "state پنهان"], controls: ["typed events", "least privilege", "audit log"],
  }),
  freezeEntry({
    id: "tool-contract", layer: "harness", kind: "standard", title: "قرارداد ابزار", subtitle: "Schema پیش از اجرا",
    summary: "نام، شرح، ورودی و خروجی ابزار باید schema معتبر، نسخه و اثر جانبی مشخص داشته باشد. خروجی مدل تا پیش از اعتبارسنجی فقط یک پیشنهاد داده‌ای است.",
    input: "tool call candidate", output: "validated arguments یا rejection",
    process: ["انتخاب ابزار مجاز", "اعتبارسنجی JSON Schema", "بررسی scope", "اجرای adapter", "اعتبارسنجی نتیجه"],
    source: "https://json-schema.org/draft/2020-12/json-schema-core", docs: "https://modelcontextprotocol.io/specification/2026-07-28/server/tools",
    relations: ["agent-harness", "tool-sandbox"], failureModes: ["آرگومان ناسازگار", "schema بیش از حد آزاد"], controls: ["additionalProperties=false", "versioned schema", "result validation"],
  }),
  freezeEntry({
    id: "tool-sandbox", layer: "harness", kind: "control", title: "Sandbox و Capability", subtitle: "کمترین اختیار لازم",
    summary: "ابزار باید در مرز جدا، با مسیرها و عملیات مجاز، سقف زمان و دادهٔ محدود اجرا شود. نام ابزار مجوز آن نیست.",
    input: "validated call + capability token", output: "bounded observation",
    process: ["resolve capability", "isolate execution", "enforce timeout", "redact output", "revoke capability"],
    source: "https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications-for-2026/", docs: "https://modelcontextprotocol.io/specification/2026-07-28/basic/authorization",
    relations: ["tool-contract", "approval-gate"], failureModes: ["prompt injection", "path traversal", "credential leakage"], controls: ["allowlist", "read-only default", "secret boundary"],
  }),
  freezeEntry({
    id: "approval-gate", layer: "harness", kind: "control", title: "Human-in-the-loop", subtitle: "توقف پیش از اثر جانبی",
    summary: "برای اقدام پرخطر، Run باید در وضعیت قابل ادامه متوقف شود؛ کاربر هدف، آرگومان، دامنه و اثر را می‌بیند و رد یا تأیید ثبت‌شده می‌دهد.",
    input: "proposed side effect + risk", output: "grant، deny یا expiry",
    process: ["طبقه‌بندی ریسک", "نمایش اثر", "توقف durable", "تصمیم انسان", "اجرای دقیق همان درخواست"],
    source: "https://modelcontextprotocol.io/specification/2026-07-28/server/tools", docs: "https://langchain-ai.github.io/langgraph/concepts/human_in_the_loop/",
    relations: ["agent-harness", "durable-run"], failureModes: ["تأیید مبهم", "تغییر آرگومان پس از تأیید"], controls: ["immutable proposal", "expiry", "two-person rule"],
  }),
  freezeEntry({
    id: "context-compiler", layer: "context", kind: "pattern", title: "Context Compiler", subtitle: "انتخاب آگاهانه، نه انباشتن همه‌چیز",
    summary: "منابع ناهمگون به واحدهای دارای منشأ، سطح اعتماد و اولویت تبدیل می‌شوند؛ سپس dedupe، رتبه‌بندی، بودجه‌بندی و بسته‌بندی می‌شوند.",
    input: "system policy + history + memory + retrieved docs + tool results", output: "context manifest + model input",
    process: ["ثبت provenance", "فیلتر اعتماد", "حذف تکرار", "رتبه‌بندی", "بستن بسته در سقف token"],
    source: "https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents", docs: "https://modelcontextprotocol.io/specification/2026-07-28/architecture",
    relations: ["context-budget", "context-provenance", "retrieval-rerank", "context-compaction"], failureModes: ["context poisoning", "دستورهای متعارض"], controls: ["source labels", "priority tiers", "manifest"],
  }),
  freezeEntry({
    id: "context-budget", layer: "context", kind: "control", title: "بودجهٔ Context", subtitle: "Token یک منبع محدود است",
    summary: "هر منبع سهم و اولویت دارد. قرارگرفتن متن در پنجره به معنی استفادهٔ درست مدل از آن نیست؛ جایگاه و تراکم نیز اهمیت دارد.",
    input: "candidate chunks + token limit", output: "selected chunks + dropped reasons",
    process: ["رزرو policy", "رزرو هدف", "امتیاز relevance", "پرکردن budget", "ثبت حذف‌ها"],
    source: "https://arxiv.org/abs/2307.03172", docs: "https://arxiv.org/abs/2307.03172",
    relations: ["context-compiler"], failureModes: ["lost in the middle", "حذف محدودیت مهم"], controls: ["protected slots", "position tests", "token accounting"],
  }),
  freezeEntry({
    id: "context-provenance", layer: "context", kind: "control", title: "منشأ و مرز اعتماد", subtitle: "داده با دستور یکی نیست",
    summary: "هر قطعه باید منبع، زمان، مالک، سطح اعتماد و نوع کنترل خود را حمل کند. متن بازیابی‌شده داده است و نباید خودکار به دستور سیستمی ارتقا یابد.",
    input: "raw context source", output: "typed, labelled context item",
    process: ["شناسهٔ منبع", "trust label", "instruction/data separation", "sanitization", "citation mapping"],
    source: "https://modelcontextprotocol.io/specification/2026-07-28/architecture", docs: "https://genai.owasp.org/llmrisk/llm01-prompt-injection/",
    relations: ["context-compiler", "guardrails"], failureModes: ["indirect injection", "منبع بدون زمان"], controls: ["untrusted-by-default", "quote boundary", "source hash"],
  }),
  freezeEntry({
    id: "retrieval-rerank", layer: "context", kind: "method", title: "Retrieval + Rerank", subtitle: "یافتن شاهد پیش از تولید",
    summary: "بازیابی نامزدهای نزدیک را می‌آورد؛ reranker ارتباط دقیق‌تر را می‌سنجد. سپس فقط قطعه‌های منتخب با شناسهٔ منبع وارد context می‌شوند.",
    input: "query + indexed corpus", output: "ranked evidence chunks",
    process: ["rewrite query", "hybrid retrieve", "dedupe", "rerank", "attach citations"],
    source: "https://arxiv.org/abs/2005.11401", docs: "https://github.com/facebookresearch/faiss",
    relations: ["context-compiler"], failureModes: ["منبع قدیمی", "near-neighbor نامربوط"], controls: ["freshness filter", "minimum score", "citation coverage"],
  }),
  freezeEntry({
    id: "context-compaction", layer: "context", kind: "method", title: "Compaction و Compression", subtitle: "کاهش حجم با ثبت اتلاف",
    summary: "تاریخچه یا سند می‌تواند خلاصه یا فشرده شود، اما خلاصه جای سند کامل نیست. نسخه، نسبت فشرده‌سازی و موارد حذف‌شده باید قابل ردیابی باشند.",
    input: "long history یا document", output: "compact state + pointer to original",
    process: ["تشخیص بخش محافظت‌شده", "خلاصه‌سازی", "حفظ تصمیم‌ها", "بررسی ناسازگاری", "پیوند به اصل"],
    source: "https://arxiv.org/abs/2310.05736", docs: "https://github.com/microsoft/LLMLingua",
    relations: ["context-budget", "memory-layers"], failureModes: ["حذف استثنا", "summary drift"], controls: ["loss ledger", "original pointer", "periodic refresh"],
  }),
  freezeEntry({
    id: "memory-layers", layer: "context", kind: "pattern", title: "لایه‌های حافظه", subtitle: "Working، episodic، semantic و procedural",
    summary: "حافظهٔ کاری برای Run جاری است؛ episodic رخدادها، semantic واقعیت‌های استخراج‌شده و procedural روش‌های تأییدشده را نگه می‌دارد. نوشتن حافظه باید سیاست مستقل داشته باشد.",
    input: "events + candidate facts", output: "scoped memory records",
    process: ["طبقه‌بندی", "بررسی رضایت/PII", "dedupe و version", "ذخیره", "retrieval یا expiry"],
    source: "https://arxiv.org/abs/2310.08560", docs: "https://langchain-ai.github.io/langgraph/concepts/memory/",
    relations: ["context-compiler", "durable-run"], failureModes: ["حافظهٔ غلط پایدار", "نشت بین کاربران"], controls: ["namespace", "TTL", "write gate", "correction log"],
  }),
  freezeEntry({
    id: "supervisor-workers", layer: "orchestration", kind: "pattern", title: "Supervisor / Workers", subtitle: "یک هماهنگ‌کننده، چند تخصص",
    summary: "Supervisor هدف را تقسیم و نتیجه‌ها را جمع می‌کند؛ هر Worker قرارداد ورودی/خروجی و کمترین ابزار لازم را دارد. Supervisor نباید شاهد را جعل کند.",
    input: "goal + worker registry", output: "delegated results + synthesis",
    process: ["decompose", "select worker", "dispatch", "collect", "verify and synthesize"],
    source: "https://langchain-ai.github.io/langgraph/concepts/multi_agent/", docs: "https://github.com/microsoft/autogen",
    relations: ["fanout-fanin", "handoff-routing"], failureModes: ["تکرار کار", "worker بدون context کافی"], controls: ["task contract", "ownership", "join condition"],
  }),
  freezeEntry({
    id: "handoff-routing", layer: "orchestration", kind: "pattern", title: "Router و Handoff", subtitle: "انتقال مالکیت با state صریح",
    summary: "Router مقصد را انتخاب می‌کند؛ Handoff مالکیت گفتگو یا task را به عامل دیگر می‌دهد. دلیل انتقال، context مجاز و شرط بازگشت باید ثبت شود.",
    input: "intent + state + agent capabilities", output: "route یا ownership transfer",
    process: ["classify", "match capability", "package scoped context", "transfer", "acknowledge ownership"],
    source: "https://openai.github.io/openai-agents-python/handoffs/", docs: "https://openai.github.io/openai-agents-python/multi_agent/",
    relations: ["supervisor-workers", "a2a"], failureModes: ["ping-pong", "context leakage"], controls: ["hop limit", "handoff schema", "ownership field"],
  }),
  freezeEntry({
    id: "fanout-fanin", layer: "orchestration", kind: "pattern", title: "Fan-out / Fan-in", subtitle: "موازی‌سازی با شرط Join",
    summary: "کارهای مستقل هم‌زمان اجرا می‌شوند و مرحلهٔ بعد فقط پس از شرط join روشن آغاز می‌شود؛ ترتیب تکمیل نباید با ترتیب اعتبار اشتباه شود.",
    input: "independent task set", output: "joined result set",
    process: ["تشخیص استقلال", "dispatch موازی", "جمع‌آوری", "timeout ناقص", "merge با provenance"],
    source: "https://langchain-ai.github.io/langgraph/how-tos/map-reduce/", docs: "https://docs.temporal.io/workflows",
    relations: ["supervisor-workers", "workflow-dag"], failureModes: ["partial join", "race condition"], controls: ["join policy", "deterministic merge", "cancellation"],
  }),
  freezeEntry({
    id: "workflow-dag", layer: "orchestration", kind: "pattern", title: "Workflow / DAG", subtitle: "وابستگی‌ها پیش از اجرا روشن‌اند",
    summary: "در workflow گره‌ها، یال‌ها، retry و شرط‌ها صریح‌اند؛ برای فرایند تکرارشونده قابل آزمون‌تر از تصمیم کاملاً آزاد عامل است.",
    input: "typed state + graph", output: "state transitions + terminal result",
    process: ["validate graph", "schedule ready nodes", "persist transition", "handle branch", "close terminal"],
    source: "https://docs.temporal.io/workflows", docs: "https://langchain-ai.github.io/langgraph/concepts/low_level/",
    relations: ["planner-executor", "durable-run"], failureModes: ["cycle ناخواسته", "state schema drift"], controls: ["graph validation", "state reducer", "migration"],
  }),
  freezeEntry({
    id: "debate-blackboard", layer: "orchestration", kind: "method", title: "Debate و Blackboard", subtitle: "چند دیدگاه روی state مشترک",
    summary: "عامل‌ها نامزد یا نقد تولید می‌کنند و یک adjudicator با معیار مشخص انتخاب می‌کند. افزایش تعداد صداها بدون تنوع و معیار می‌تواند فقط هزینه را زیاد کند.",
    input: "problem + roles + shared evidence", output: "candidates + adjudicated result",
    process: ["assign roles", "independent proposals", "cross critique", "evidence check", "adjudicate"],
    source: "https://arxiv.org/abs/2305.14325", docs: "https://microsoft.github.io/autogen/stable/user-guide/core-user-guide/design-patterns/group-chat.html",
    relations: ["reflection-verifier", "supervisor-workers"], failureModes: ["groupthink", "endless debate"], controls: ["round limit", "diverse evidence", "scoring rubric"],
  }),
  freezeEntry({
    id: "mcp", layer: "protocol", kind: "protocol", title: "MCP", subtitle: "Host / Client / Server برای Context و ابزار",
    summary: "MCP 2026-07-28 یک core بی‌حالت دارد: هر درخواست نسخه و capability خود را حمل می‌کند. Host همچنان مرز رضایت، authorization، policy و تجمیع context است.",
    input: "self-contained JSON-RPC request + version/capabilities", output: "resources, prompts, tools and results",
    process: ["pin protocol version", "server/discover اختیاری", "درخواست self-contained", "اعتبارسنجی response", "cache/trace"],
    source: "https://modelcontextprotocol.io/specification/2026-07-28/architecture", docs: "https://modelcontextprotocol.io/specification/2026-07-28",
    relations: ["agent-harness", "tool-contract", "context-provenance"], failureModes: ["token passthrough", "confused deputy"], controls: ["per-server isolation", "OAuth audience", "user consent"],
  }),
  freezeEntry({
    id: "a2a", layer: "protocol", kind: "protocol", title: "A2A", subtitle: "همکاری میان عامل‌های مستقل",
    summary: "A2A قابلیت، پیام، task، artifact و به‌روزرسانی عامل‌های مستقل را مبادله می‌کند؛ جزئیات داخلی عامل opaque باقی می‌ماند.",
    input: "Agent Card + Message/Task", output: "status, artifacts and streamed updates",
    process: ["discover Agent Card", "authenticate", "send message/task", "stream status", "receive artifact"],
    source: "https://a2a-protocol.org/latest/specification/", docs: "https://github.com/a2aproject/A2A",
    relations: ["handoff-routing", "agent-harness"], failureModes: ["capability mismatch", "identity ambiguity"], controls: ["Agent Card validation", "auth", "task idempotency"],
  }),
  freezeEntry({
    id: "ag-ui", layer: "protocol", kind: "protocol", title: "AG-UI", subtitle: "رویدادهای عامل برای رابط زنده",
    summary: "AG-UI جریان رویداد اجرای عامل را برای UI استاندارد می‌کند: lifecycle، متن، ابزار، state و activity. رابط باید event را نمایش دهد، نه state حدس‌زده را.",
    input: "agent event stream", output: "interactive UI state",
    process: ["run started", "stream events", "render tool/state", "interrupt/input", "run finished"],
    source: "https://docs.ag-ui.com/concepts/events", docs: "https://github.com/ag-ui-protocol/ag-ui",
    relations: ["agent-harness", "trace-spans"], failureModes: ["event reorder", "UI/state divergence"], controls: ["sequence id", "snapshot + delta", "terminal event"],
  }),
  freezeEntry({
    id: "durable-run", layer: "reliability", kind: "control", title: "Durable Execution", subtitle: "Checkpoint، resume و idempotency",
    summary: "Run طولانی باید پس از توقف فرایند از checkpoint معتبر ادامه یابد. تکرار فعالیت اثرگذار باید idempotent یا دارای کلید یکتا باشد.",
    input: "event history + checkpoint", output: "resumed deterministic state",
    process: ["persist event", "save checkpoint", "detect restart", "replay state", "resume pending activity"],
    source: "https://docs.temporal.io/workflows", docs: "https://docs.temporal.io/workflow-execution",
    relations: ["agent-harness", "workflow-dag", "retry-circuit"], failureModes: ["double side effect", "stale checkpoint"], controls: ["idempotency key", "event history", "version marker"],
  }),
  freezeEntry({
    id: "retry-circuit", layer: "reliability", kind: "control", title: "Retry / Backoff / Circuit Breaker", subtitle: "خطا را بی‌نهایت تکرار نکن",
    summary: "خطای موقت با backoff محدود قابل تکرار است؛ خطای سیاست یا ورودی نباید retry شود. Circuit breaker از فشار مداوم بر سرویس خراب جلوگیری می‌کند.",
    input: "classified failure", output: "retry, fallback یا fail closed",
    process: ["classify", "check retry budget", "backoff+jitter", "retry idempotently", "open circuit/fallback"],
    source: "https://docs.temporal.io/encyclopedia/retry-policies", docs: "https://opentelemetry.io/docs/specs/semconv/general/recording-errors/",
    relations: ["durable-run", "budget-cancel"], failureModes: ["retry storm", "تکرار پرداخت"], controls: ["maxAttempts", "nonRetryableErrors", "idempotency"],
  }),
  freezeEntry({
    id: "budget-cancel", layer: "reliability", kind: "control", title: "Budget، Deadline و Cancellation", subtitle: "پایان، بخشی از معماری است",
    summary: "Run باید سقف step، token، زمان، هزینه و concurrency داشته باشد. لغو باید به worker و ابزار منتشر و نتیجهٔ نیمه‌تمام صریح ثبت شود.",
    input: "run policy + live usage", output: "continue, degrade یا cancel",
    process: ["reserve budget", "meter usage", "warn threshold", "propagate cancel", "close resources"],
    source: "https://opentelemetry.io/docs/specs/semconv/gen-ai/", docs: "https://docs.temporal.io/develop/python/cancellation",
    relations: ["agent-harness", "fanout-fanin"], failureModes: ["orphan worker", "unbounded cost"], controls: ["hard cap", "deadline", "cancellation token"],
  }),
  freezeEntry({
    id: "guardrails", layer: "reliability", kind: "control", title: "Guardrails چندلایه", subtitle: "ورودی، خروجی، ابزار و اثر",
    summary: "Guardrail فقط فیلتر متن نیست: ورودی و PII، خروجی ساختاری، انتخاب ابزار، آرگومان و اثر واقعی هرکدام مرز مستقل می‌خواهند.",
    input: "input/output/action candidate", output: "allow, transform, escalate یا block",
    process: ["classify surface", "apply deterministic checks", "policy/model check", "record reason", "block or continue"],
    source: "https://openai.github.io/openai-agents-python/guardrails/", docs: "https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications-for-2026/",
    relations: ["approval-gate", "context-provenance", "eval-gates"], failureModes: ["false allow", "silent mutation"], controls: ["fail closed", "reason code", "red-team suite"],
  }),
  freezeEntry({
    id: "trace-spans", layer: "observability", kind: "standard", title: "Trace و Span", subtitle: "Run قابل بازسازی، نه ذهن قابل خواندن",
    summary: "هر model call، tool call، handoff و guardrail یک span با شناسه و رابطهٔ والد دارد. Trace رویداد و دادهٔ ثبت‌شده را نشان می‌دهد، نه استدلال پنهان مدل.",
    input: "runtime events + attributes", output: "traces, metrics and logs",
    process: ["create trace", "start span", "attach safe attributes", "record status/error", "export or inspect"],
    source: "https://opentelemetry.io/docs/specs/semconv/gen-ai/", docs: "https://www.w3.org/TR/trace-context/",
    relations: ["agent-harness", "ag-ui", "eval-gates"], failureModes: ["PII in trace", "missing parent"], controls: ["redaction", "sampling policy", "traceparent"],
  }),
  freezeEntry({
    id: "eval-gates", layer: "observability", kind: "method", title: "Evals و Release Gates", subtitle: "کیفیت با سناریو و معیار",
    summary: "آزمون واحد ابزار، شبیه‌سازی workflow، replay trace، مجموعهٔ ارزیابی، امنیت و آزمون انسانی لایه‌های متفاوت‌اند؛ یک نمره جای همه را نمی‌گیرد.",
    input: "scenarios + expected invariants", output: "scores, failures and release decision",
    process: ["define task", "freeze dataset", "run/replay", "grade with evidence", "compare regression"],
    source: "https://github.com/openai/evals", docs: "https://www.nist.gov/itl/ai-risk-management-framework",
    relations: ["reflection-verifier", "trace-spans", "guardrails"], failureModes: ["benchmark leakage", "metric gaming"], controls: ["held-out cases", "human audit", "failure taxonomy"],
  }),
]);

export const AGENTIC_BY_ID = new Map(AGENTIC_CATALOG.map((item) => [item.id, item]));

export const AGENTIC_RELATIONS = Object.freeze(
  AGENTIC_CATALOG.flatMap((item) => item.relations.map((target) => Object.freeze({
    id: `${item.id}--${target}`,
    from: item.id,
    to: target,
  }))),
);
