export const CATEGORIES = Object.freeze({
  foundation: { label: "بنیادها", color: 0xb9f227, orbit: 15 },
  text: { label: "زبان و استدلال", color: 0x62d9ce, orbit: 23 },
  image: { label: "تصویر", color: 0xf39a53, orbit: 31 },
  video: { label: "ویدئو", color: 0xff6b58, orbit: 39 },
  audio: { label: "صدا و گفتار", color: 0xd6a6ff, orbit: 47 },
  code: { label: "کد", color: 0x72a7ff, orbit: 55 },
  multimodal: { label: "چندوجهی", color: 0xffd166, orbit: 63 },
  system: { label: "اجرا و زیست‌بوم", color: 0x9eaaa1, orbit: 71 },
  agentic: { label: "سامانه‌های عامل‌محور", color: 0xffc857, orbit: 79 },
});

const DEFAULT_SOURCE = "https://github.com/huggingface/transformers";

function node(spec) {
  return Object.freeze({
    status: "source-backed",
    license: "مجوز کد و وزن/داده را جدا بررسی کنید.",
    paper: null,
    exhibit: "graph",
    params: "وابسته به پیاده‌سازی",
    compute: "وابسته به اندازه، دقت عددی و سخت‌افزار",
    data: "دادهٔ آموزشی یا ورودی باید مستقل ممیزی شود.",
    parents: [],
    tags: [],
    ...spec,
  });
}

export const MODEL_CATALOG = Object.freeze([
  node({
    id: "data-lifecycle", category: "foundation", title: "چرخهٔ حیات داده", subtitle: "از منبع تا split و provenance",
    summary: "داده پیش از مدل می‌آید: جمع‌آوری، مجوز، پاک‌سازی، حذف تکرار، برچسب‌گذاری، split و versioning تعیین می‌کنند مدل چه الگوهایی را اصلاً ببیند.",
    architecture: "pipeline داده و حاکمیت، نه شبکهٔ عصبی", input: "متن، تصویر، ویدئو، صدا، کد و metadata", output: "dataset نسخه‌دار + manifest + split",
    process: ["ثبت منبع و مجوز", "پاک‌سازی و حذف تکرار", "کیفیت/ایمنی", "تقسیم train/validation/test", "hash و provenance"],
    repo: "https://github.com/huggingface/datasets", license: "کتابخانه Apache-2.0؛ هر dataset مجوز خودش را دارد.", tags: ["dataset", "governance", "split"],
  }),
  node({
    id: "tokenizer", category: "foundation", title: "Tokenizer", subtitle: "پل داده و مدل",
    summary: "رشته یا رسانه را به شناسه‌های گسسته تبدیل می‌کند. مرز tokenها مستقیماً روی طول context، هزینه و توان بازنمایی اثر دارد.",
    architecture: "BPE / Unigram / WordPiece / codec tokenizer", input: "دادهٔ خام", output: "token IDs + offsets",
    process: ["normalization", "pre-tokenization", "merge/model", "ID lookup", "attention mask"], repo: "https://github.com/huggingface/tokenizers",
    license: "Apache-2.0", tags: ["BPE", "vocabulary", "tokens"], parents: ["data-lifecycle"],
  }),
  node({
    id: "embedding", category: "foundation", title: "Embedding", subtitle: "شناسه به بردار پیوسته",
    summary: "جدول embedding هر token ID را به برداری قابل‌آموزش می‌برد؛ شباهت هندسی می‌تواند مفید باشد اما به‌تنهایی معنای انسانی یا حقیقت نیست.",
    architecture: "lookup table + positional representation", input: "token IDs", output: "sequence of vectors",
    process: ["lookup", "position encoding", "normalization", "ورود به backbone"], repo: DEFAULT_SOURCE, tags: ["vectors", "position"], parents: ["tokenizer"],
  }),
  node({
    id: "dense-transformer", category: "foundation", title: "Transformer چگال", subtitle: "Attention + MLP برای هر token",
    summary: "در لایهٔ چگال همهٔ tokenها از attention و MLP یکسان عبور می‌کنند. وزن فعال تقریباً همان وزن کل است.",
    architecture: "decoder-only یا encoder/decoder Transformer", input: "بردارهای token", output: "hidden states / logits",
    process: ["RMS/LayerNorm", "causal self-attention", "residual", "dense MLP", "logit projection"], repo: DEFAULT_SOURCE,
    paper: "https://arxiv.org/abs/1706.03762", tags: ["attention", "dense", "autoregressive"], parents: ["embedding"],
  }),
  node({
    id: "sparse-moe", category: "foundation", title: "Sparse Mixture-of-Experts", subtitle: "وزن کل زیاد، مسیر فعال محدود",
    summary: "Router برای هر token چند expert را انتخاب می‌کند. همهٔ expertها باید ذخیره شوند، ولی فقط زیرمجموعه‌ای در محاسبهٔ همان token فعال است.",
    architecture: "shared attention + routed expert MLPs", input: "hidden state هر token", output: "ترکیب خروجی expertهای منتخب",
    process: ["router logits", "top-k expert selection", "expert MLP", "weighted merge", "load balancing"], repo: "https://github.com/deepseek-ai/DeepSeek-V3",
    paper: "https://arxiv.org/abs/2405.04434", params: "کل ≠ فعال در هر token", compute: "حافظهٔ کل expertها + محاسبهٔ expertهای فعال", tags: ["router", "experts", "sparse"], parents: ["dense-transformer"], exhibit: "moe",
  }),
  node({
    id: "mla", category: "foundation", title: "Multi-head Latent Attention", subtitle: "فشرده‌سازی نمایش KV",
    summary: "MLA در خانوادهٔ DeepSeek نمایش‌های key/value را به فضای latent فشرده می‌کند تا KV cache و هزینهٔ inference کاهش یابد.",
    architecture: "latent compression around multi-head attention", input: "query و hidden state", output: "attention context",
    process: ["down projection", "latent KV", "head-specific reconstruction", "attention", "output projection"], repo: "https://github.com/deepseek-ai/DeepSeek-V3",
    paper: "https://arxiv.org/abs/2405.04434", tags: ["KV cache", "attention", "DeepSeek"], parents: ["dense-transformer"],
  }),
  node({
    id: "state-space", category: "foundation", title: "State Space / Mamba", subtitle: "انتقال state با رشد خطی",
    summary: "مدل state-space به‌جای ساخت ماتریس attention کامل، state فشرده‌ای را در طول دنباله انتقال می‌دهد؛ selective SSM ورودی‌محور تصمیم می‌گیرد چه چیزی حفظ شود.",
    architecture: "selective state-space model", input: "sequence embeddings", output: "sequence states",
    process: ["input projection", "selective parameters", "state scan", "gating", "output projection"], repo: "https://github.com/state-spaces/mamba",
    paper: "https://arxiv.org/abs/2312.00752", tags: ["SSM", "linear time", "state"], parents: ["embedding"],
  }),
  node({
    id: "diffusion-core", category: "foundation", title: "Diffusion / Denoising", subtitle: "یادگیری بازگرداندن نویز",
    summary: "مدل از نویز شروع و طی چند گام با تخمین noise/velocity/sample آن را به نمونهٔ سازگار با شرط تبدیل می‌کند. scheduler و denoiser دو جزء متفاوت‌اند.",
    architecture: "iterative generative process with U-Net or DiT", input: "noise + conditioning", output: "sample یا latent پاک‌شده",
    process: ["sample noise", "predict residual", "scheduler step", "repeat", "decode"], repo: "https://github.com/huggingface/diffusers",
    paper: "https://arxiv.org/abs/2006.11239", tags: ["denoise", "scheduler", "U-Net", "DiT"], exhibit: "diffusion",
  }),
  node({
    id: "flow-matching", category: "foundation", title: "Flow Matching", subtitle: "میدان برداری از نویز به داده",
    summary: "به‌جای تفسیر زنجیره به‌عنوان denoising احتمالاتی، یک velocity field پیوسته برای انتقال توزیع ساده به توزیع داده آموخته می‌شود.",
    architecture: "continuous normalizing flow / rectified flow", input: "noise + time + condition", output: "trajectory toward sample",
    process: ["choose path", "train velocity", "ODE integration", "latent sample", "decode"], repo: "https://github.com/black-forest-labs/flux",
    paper: "https://arxiv.org/abs/2210.02747", tags: ["ODE", "velocity", "rectified flow"], parents: ["diffusion-core"], exhibit: "diffusion",
  }),

  node({
    id: "deepseek-v3", category: "text", title: "DeepSeek-V3", subtitle: "MoE عظیم با MLA و MTP",
    summary: "طبق مخزن رسمی، V3 دارای ۶۷۱ میلیارد پارامتر کل و ۳۷ میلیارد پارامتر فعال در هر token است. MLA، DeepSeekMoE و هدف multi-token prediction اجزای کلیدی‌اند.",
    architecture: "decoder-only Transformer + sparse DeepSeekMoE + MLA", input: "text tokens", output: "next-token distribution",
    process: ["tokenize", "MLA attention", "route to experts", "residual layers", "MTP/main logits", "sample token"], repo: "https://github.com/deepseek-ai/DeepSeek-V3",
    paper: "https://arxiv.org/abs/2412.19437", license: "کد MIT؛ وزن‌ها و شرایط استفاده را از LICENSE-MODEL همان مخزن بخوانید.", params: "671B total / 37B activated", compute: "مخزن رسمی inference مرجع را برای Linux و چند GPU توصیف می‌کند؛ full model مصرف‌کننده‌ای نیست.",
    data: "مخزن رسمی 14.8T token پیش‌آموزش را گزارش می‌کند؛ dataset خام عمومی کامل نیست.", tags: ["DeepSeek", "MoE", "MLA", "MTP"], parents: ["sparse-moe", "mla"], exhibit: "moe",
  }),
  node({
    id: "deepseek-r1", category: "text", title: "DeepSeek-R1", subtitle: "Reasoning post-training روی V3-Base",
    summary: "R1 بر پایهٔ V3-Base ساخته شده و pipeline رسمی آن cold-start data، مراحل RL و SFT را ترکیب می‌کند. متن reasoning تولیدشده رفتار خروجی است، نه دسترسی به حالت ذهنی پنهان.",
    architecture: "DeepSeek-V3 MoE backbone + reasoning post-training", input: "prompt tokens", output: "generated reasoning text + answer tokens",
    process: ["base checkpoint", "cold-start SFT", "reasoning RL", "rejection/supervised data", "alignment RL", "inference"], repo: "https://github.com/deepseek-ai/DeepSeek-R1",
    paper: "https://arxiv.org/abs/2501.12948", license: "مخزن MIT؛ مدل‌های مشتق ممکن است تابع مجوز base باشند.", params: "671B total / 37B activated", compute: "وزن کامل حتی با expertهای sparse باید در حافظه/ذخیره‌سازی قابل دسترس باشد.",
    tags: ["reasoning", "RL", "DeepSeek"], parents: ["deepseek-v3"], exhibit: "cpu",
  }),
  node({
    id: "deepseek-r1-distill", category: "text", title: "R1 Distill", subtitle: "Reasoning data روی مدل dense کوچک‌تر",
    summary: "مخزن رسمی checkpointهای dense با اندازه‌های ۱٫۵، ۷، ۸، ۱۴، ۳۲ و ۷۰ میلیارد پارامتر بر پایهٔ Qwen/Llama منتشر کرده است؛ این‌ها معماری ۶۷۱B MoE را حفظ نمی‌کنند.",
    architecture: "dense Qwen/Llama backbone fine-tuned on R1-generated data", input: "text tokens", output: "autoregressive text",
    process: ["teacher reasoning data", "filter", "dense student SFT", "quantize optionally", "CPU/GPU inference"], repo: "https://github.com/deepseek-ai/DeepSeek-R1",
    paper: "https://arxiv.org/abs/2501.12948", license: "مجوز base مدل Qwen یا Llama همراه مجوز R1 بررسی شود.", params: "1.5B / 7B / 8B / 14B / 32B / 70B", compute: "نسخه‌های کوچک quantized می‌توانند با llama.cpp روی CPU اجرا شوند؛ سرعت تابع RAM و پهنای‌باند است.",
    tags: ["distillation", "GGUF", "CPU"], parents: ["deepseek-r1", "dense-transformer"], exhibit: "cpu",
  }),
  node({
    id: "llama-family", category: "text", title: "Llama family", subtitle: "Decoder-only dense foundation models",
    summary: "خانواده‌ای از Transformerهای decoder-only چگال که نسخه‌ها و مجوزهای متفاوت دارند؛ اکوسیستم GGUF و ابزارهای محلی گسترده‌ای پیرامون آن ساخته شده است.",
    architecture: "dense decoder-only Transformer with GQA in newer generations", input: "tokens", output: "next-token logits",
    process: ["embedding", "causal attention", "SwiGLU MLP", "repeat layers", "LM head"], repo: "https://github.com/meta-llama/llama-models",
    license: "وزن‌ها تحت مجوز جامعهٔ Llama هستند، نه MIT/Apache عمومی.", tags: ["dense", "GQA", "local"], parents: ["dense-transformer"],
  }),
  node({
    id: "qwen-family", category: "text", title: "Qwen family", subtitle: "مدل‌های dense/MoE چندزبانه",
    summary: "خانواده‌ای از مدل‌های زبانی و چندوجهی با اندازه‌ها و معماری‌های گوناگون؛ R1 Distill چند checkpoint را بر پایهٔ Qwen2.5 ساخته است.",
    architecture: "decoder-only dense or MoE depending checkpoint", input: "text/multimodal tokens", output: "generated tokens",
    process: ["tokenization", "attention", "MLP/MoE", "logits", "sampling"], repo: "https://github.com/QwenLM/Qwen3",
    license: "مجوز هر checkpoint جداگانه بررسی شود.", tags: ["multilingual", "dense", "MoE"], parents: ["dense-transformer", "sparse-moe"],
  }),
  node({
    id: "mistral-family", category: "text", title: "Mistral / Mixtral", subtitle: "Dense و sparse MoE",
    summary: "Mistral معماری‌های dense و Mixtral معماری sparse MoE را نشان می‌دهند؛ sliding-window/GQA و expert routing بسته به نسخه متفاوت است.",
    architecture: "decoder-only Transformer; dense or sparse MoE", input: "tokens", output: "logits",
    process: ["attention", "router if MoE", "expert/dense MLP", "residual", "decode"], repo: "https://github.com/mistralai/mistral-inference",
    license: "کد Apache-2.0؛ مجوز checkpoint جداست.", tags: ["Mistral", "Mixtral", "MoE"], parents: ["dense-transformer", "sparse-moe"],
  }),

  node({
    id: "latent-diffusion", category: "image", title: "Latent Diffusion", subtitle: "Denoising در فضای فشرده",
    summary: "VAE تصویر را به latent کوچک‌تر می‌برد؛ denoiser در همان فضا کار می‌کند و در پایان decoder آن را به pixel بازمی‌گرداند.",
    architecture: "text encoder + latent U-Net/DiT + VAE", input: "prompt + latent noise", output: "image pixels",
    process: ["encode prompt", "sample latent noise", "iterative denoise", "VAE decode", "postprocess"], repo: "https://github.com/CompVis/latent-diffusion",
    paper: "https://arxiv.org/abs/2112.10752", tags: ["VAE", "latent", "U-Net"], parents: ["diffusion-core"], exhibit: "diffusion",
  }),
  node({
    id: "stable-diffusion", category: "image", title: "Stable Diffusion", subtitle: "Text-conditioned latent diffusion",
    summary: "پیاده‌سازی شناخته‌شدهٔ latent diffusion که text embedding از راه cross-attention denoiser را شرطی می‌کند.",
    architecture: "CLIP text encoder + latent U-Net + VAE + scheduler", input: "text / image condition + seed", output: "generated image",
    process: ["text embedding", "latent noise", "cross-attention denoise", "guidance", "VAE decode"], repo: "https://github.com/CompVis/stable-diffusion",
    paper: "https://arxiv.org/abs/2112.10752", license: "کد و وزن‌ها مجوزهای متفاوت دارند؛ model card را بررسی کنید.", tags: ["image", "cross-attention", "CFG"], parents: ["latent-diffusion"], exhibit: "diffusion",
  }),
  node({
    id: "flux", category: "image", title: "FLUX", subtitle: "Transformer مبتنی بر flow matching",
    summary: "خانوادهٔ FLUX نمونه‌ای از مدل‌های تصویر مبتنی بر transformer و جریان/rectified flow است؛ اصطلاح «diffusion» در کاربرد عام همهٔ جزئیات آموزش آن را توضیح نمی‌دهد.",
    architecture: "multimodal diffusion/flow transformer", input: "text embeddings + noise", output: "image latent سپس pixels",
    process: ["condition encode", "noise state", "velocity prediction", "ODE/scheduler steps", "decode"], repo: "https://github.com/black-forest-labs/flux",
    license: "کد Apache-2.0؛ مجوز وزن هر variant متفاوت است.", tags: ["flow", "DiT", "image"], parents: ["flow-matching"], exhibit: "diffusion",
  }),
  node({
    id: "controlnet", category: "image", title: "ControlNet", subtitle: "شرط ساختاری کنار denoiser منجمد",
    summary: "مسیر کنترلی از edge/depth/pose ویژگی می‌سازد و آن را به denoiser اضافه می‌کند تا ساختار خروجی هدایت شود.",
    architecture: "trainable control branch attached to pretrained diffusion model", input: "prompt + control map + noise", output: "structure-guided image",
    process: ["extract condition", "control encoder", "zero convolutions", "inject residuals", "denoise"], repo: "https://github.com/lllyasviel/ControlNet",
    paper: "https://arxiv.org/abs/2302.05543", tags: ["depth", "pose", "edge"], parents: ["stable-diffusion"], exhibit: "diffusion",
  }),
  node({
    id: "comfyui", category: "image", title: "ComfyUI", subtitle: "زیست‌بوم گراف workflow",
    summary: "ComfyUI خودِ مدل مولد نیست؛ node graph برای اتصال loader، encoder، sampler، scheduler، VAE، control و ذخیرهٔ خروجی است.",
    architecture: "host-side directed workflow graph", input: "workflow + models + media", output: "executed artifacts and metadata",
    process: ["load workflow", "resolve nodes", "cache dependencies", "execute graph", "save provenance"], repo: "https://github.com/Comfy-Org/ComfyUI",
    license: "GPL-3.0", tags: ["workflow", "nodes", "ecosystem"], parents: ["stable-diffusion", "flux"], exhibit: "graph",
  }),

  node({
    id: "video-dit", category: "video", title: "Video Diffusion Transformer", subtitle: "فضا + زمان در latent",
    summary: "ویدئو علاوه بر ساختار فضایی باید پیوستگی زمانی را حفظ کند. latentهای چند frame و attention/blocks زمانی هزینه را نسبت به تصویر بالا می‌برند.",
    architecture: "spatiotemporal DiT + video VAE", input: "text/keyframe + video noise", output: "latent frames سپس video",
    process: ["condition", "3D/temporal latent", "spatiotemporal denoise", "video VAE decode", "frames"], repo: "https://github.com/huggingface/diffusers",
    paper: "https://arxiv.org/abs/2212.09748", tags: ["temporal", "frames", "DiT"], parents: ["diffusion-core"], exhibit: "video",
  }),
  node({
    id: "hunyuan-video", category: "video", title: "HunyuanVideo", subtitle: "چارچوب متن‌به‌ویدئوی DiT",
    summary: "مخزن رسمی تعریف مدل، وزن و sampling را منتشر می‌کند و integrationهایی مانند Diffusers و ComfyUI پیرامون آن شکل گرفته‌اند.",
    architecture: "large video diffusion transformer + 3D VAE", input: "prompt + optional image/audio conditions", output: "video frames",
    process: ["text encode", "latent initialize", "DiT denoise", "3D VAE decode", "video assemble"], repo: "https://github.com/Tencent-Hunyuan/HunyuanVideo",
    paper: "https://arxiv.org/abs/2412.03603", license: "مجوز اختصاصی مخزن/مدل؛ پیش از استفادهٔ تجاری بررسی شود.", params: "نسخه‌ها متفاوت‌اند", compute: "عمدتاً GPU-heavy؛ quantization/offload کیفیت و زمان را معامله می‌کند.", tags: ["video", "DiT", "3D VAE"], parents: ["video-dit"], exhibit: "video",
  }),
  node({
    id: "cogvideox", category: "video", title: "CogVideoX", subtitle: "Expert Transformer برای text-to-video",
    summary: "CogVideoX یک diffusion transformer و 3D causal VAE برای فشرده‌سازی ویدئو دارد؛ مدل caption/condition و backbone اجزای جدا هستند.",
    architecture: "expert diffusion transformer + 3D causal VAE", input: "text/image condition + noise", output: "video",
    process: ["caption/text encode", "3D latent", "expert transformer denoise", "causal VAE decode", "frames"], repo: "https://github.com/zai-org/CogVideo",
    paper: "https://arxiv.org/abs/2408.06072", license: "کد Apache-2.0؛ weight/model license جدا بررسی شود.", tags: ["video", "expert transformer", "VAE"], parents: ["video-dit"], exhibit: "video",
  }),
  node({
    id: "wan21", category: "video", title: "Wan 2.1", subtitle: "مجموعهٔ باز تولید ویدئو",
    summary: "مخزن رسمی variantهای text-to-video، image-to-video و دیگر workflowها را با اندازه‌های متفاوت ارائه می‌کند؛ 1.3B و 14B نیاز سخت‌افزاری یکسان ندارند.",
    architecture: "video diffusion transformer suite", input: "text / image / frame conditions", output: "video",
    process: ["condition", "video latent", "iterative generation", "decode", "temporal output"], repo: "https://github.com/Wan-Video/Wan2.1",
    paper: "https://arxiv.org/abs/2503.20314", license: "Apache-2.0 برای کد مخزن؛ شرایط وزن‌ها را نیز بررسی کنید.", params: "1.3B و 14B variantها", compute: "نسخهٔ 1.3B سبک‌تر است؛ resolution و طول زمان RAM/VRAM را شدیداً تغییر می‌دهند.", tags: ["T2V", "I2V", "video"], parents: ["video-dit"], exhibit: "video",
  }),

  node({
    id: "whisper", category: "audio", title: "Whisper", subtitle: "گفتار به متن encoder–decoder",
    summary: "موج صدا به log-Mel spectrogram تبدیل می‌شود؛ encoder ویژگی‌های صوتی و decoder autoregressive متن/زمان/زبان را تولید می‌کند.",
    architecture: "audio encoder + autoregressive text decoder Transformer", input: "waveform / log-Mel", output: "transcript + optional timestamps",
    process: ["resample", "log-Mel", "audio encoder", "text decoder", "token decode"], repo: "https://github.com/openai/whisper",
    paper: "https://arxiv.org/abs/2212.04356", license: "MIT", tags: ["ASR", "spectrogram", "encoder-decoder"], parents: ["dense-transformer"], exhibit: "audio",
  }),
  node({
    id: "encodec", category: "audio", title: "EnCodec", subtitle: "Neural audio codec و tokenهای صوتی",
    summary: "Encoder موج را فشرده، residual vector quantizer آن را به codeهای گسسته تبدیل و decoder دوباره waveform می‌سازد.",
    architecture: "convolutional autoencoder + residual vector quantization", input: "waveform", output: "codec tokens یا reconstructed audio",
    process: ["audio encoder", "quantizer stacks", "discrete codes", "decoder", "waveform"], repo: "https://github.com/facebookresearch/encodec",
    paper: "https://arxiv.org/abs/2210.13438", license: "MIT", tags: ["codec", "RVQ", "audio tokens"], exhibit: "audio",
  }),
  node({
    id: "audiocraft", category: "audio", title: "AudioCraft / MusicGen", subtitle: "LM روی tokenهای codec",
    summary: "MusicGen به‌جای تولید مستقیم sampleهای waveform، توالی codeهای EnCodec را با Transformer شرطی تولید و سپس codec آن‌ها را decode می‌کند.",
    architecture: "autoregressive Transformer over neural audio codec tokens", input: "text/melody condition", output: "audio token streams سپس waveform",
    process: ["condition encode", "predict codec tokens", "multi-codebook pattern", "EnCodec decode", "audio"], repo: "https://github.com/facebookresearch/audiocraft",
    paper: "https://arxiv.org/abs/2306.05284", license: "کد MIT؛ وزن‌ها CC-BY-NC 4.0 گزارش شده‌اند.", tags: ["music", "codec LM", "MusicGen"], parents: ["encodec", "dense-transformer"], exhibit: "audio",
  }),
  node({
    id: "bark", category: "audio", title: "Bark", subtitle: "Semantic → coarse → fine audio tokens",
    summary: "Bark چند مرحلهٔ Transformer برای tokenهای معنایی و codec به‌کار می‌گیرد و می‌تواند گفتار و دیگر نشانه‌های صوتی را در یک فرایند بسازد.",
    architecture: "hierarchical GPT-style token generators + audio codec", input: "text", output: "audio tokens سپس waveform",
    process: ["text/semantic tokens", "coarse codec tokens", "fine codec tokens", "codec decode", "waveform"], repo: "https://github.com/suno-ai/bark",
    license: "MIT برای کد؛ مدل و کاربرد مسئولیت مستقل دارند.", tags: ["TTS", "audio LM", "hierarchy"], parents: ["encodec", "dense-transformer"], exhibit: "audio",
  }),
  node({
    id: "audio-diffusion", category: "audio", title: "Audio Diffusion", subtitle: "Denoising spectrogram یا audio latent",
    summary: "Diffusion می‌تواند روی waveform، spectrogram یا latent صوتی اجرا شود؛ decoder یا vocoder نمایش میانی را به موج برمی‌گرداند.",
    architecture: "conditional diffusion + audio representation decoder", input: "noise + text/audio condition", output: "spectrogram/latent سپس waveform",
    process: ["noise", "condition", "iterative denoise", "vocoder/decoder", "audio"], repo: "https://github.com/huggingface/diffusers",
    tags: ["diffusion", "spectrogram", "vocoder"], parents: ["diffusion-core"], exhibit: "audio",
  }),

  node({
    id: "starcoder2", category: "code", title: "StarCoder2", subtitle: "Code LM با Fill-in-the-Middle",
    summary: "مدل decoder-only روی دادهٔ کد آموزش می‌بیند و علاوه بر left-to-right می‌تواند با FIM بخش میانی فایل را با دیدن prefix و suffix تکمیل کند.",
    architecture: "dense decoder-only Transformer", input: "code/text tokens + FIM sentinels", output: "code tokens",
    process: ["repository data", "FIM transform", "causal training", "prompt", "code generation"], repo: "https://github.com/bigcode-project/starcoder2",
    paper: "https://arxiv.org/abs/2402.19173", license: "کد Apache-2.0؛ مدل BigCode OpenRAIL-M و دادهٔ The Stack شرایط جدا دارند.", tags: ["code", "FIM", "BigCode"], parents: ["dense-transformer"], exhibit: "code",
  }),
  node({
    id: "deepseek-coder-v2", category: "code", title: "DeepSeek-Coder-V2", subtitle: "Code MoE با context بلند",
    summary: "خانوادهٔ code-specialized مبتنی بر DeepSeek-V2 که variantهای MoE دارد؛ repository-level completion و code reasoning به داده/پس‌آموزش تخصصی تکیه دارند.",
    architecture: "decoder-only DeepSeekMoE code model", input: "code + natural language tokens", output: "code/text tokens",
    process: ["code corpus", "FIM/repository objectives", "MoE routing", "decoding", "optional tests/tools"], repo: "https://github.com/deepseek-ai/DeepSeek-Coder-V2",
    paper: "https://arxiv.org/abs/2406.11931", license: "کد MIT؛ مجوز مدل در مخزن بررسی شود.", tags: ["code", "MoE", "FIM"], parents: ["sparse-moe"], exhibit: "code",
  }),
  node({
    id: "code-llama", category: "code", title: "Code Llama", subtitle: "Code-specialized Llama",
    summary: "مدل dense مشتق از Llama که variantهای code completion و instruction دارد؛ اجرای کد بخشی از شبکه نیست و باید در sandbox میزبان انجام شود.",
    architecture: "dense decoder-only Transformer", input: "code/text tokens", output: "code tokens",
    process: ["code pretraining", "optional infilling", "instruction tuning", "decode", "host validation"], repo: "https://github.com/meta-llama/codellama",
    paper: "https://arxiv.org/abs/2308.12950", license: "مجوز اختصاصی Code Llama؛ MIT نیست.", tags: ["code", "Llama", "infilling"], parents: ["llama-family"], exhibit: "code",
  }),
  node({
    id: "code-agent-loop", category: "code", title: "عامل کدنویسی", subtitle: "Model + repository + tools + tests",
    summary: "توان عامل کد فقط از LM نیست: ارکستریتور فایل‌ها را می‌خواند، patch می‌سازد، ابزار را با مجوز اجرا و test result را دوباره به مدل برمی‌گرداند.",
    architecture: "host-controlled plan/act/observe loop", input: "task + repository state + policy", output: "patch + evidence",
    process: ["inspect", "plan", "generate patch", "sandboxed tools", "tests", "review/revise"], repo: "https://github.com/openai/openai-agents-python",
    license: "MIT برای SDK؛ امنیت اجرا به میزبان وابسته است.", tags: ["agent", "tools", "tests"], parents: ["starcoder2", "deepseek-coder-v2"], exhibit: "code",
  }),

  node({
    id: "clip", category: "multimodal", title: "CLIP", subtitle: "Dual encoder contrastive",
    summary: "یک encoder متن و یک encoder تصویر بردارهایی می‌سازند که زوج‌های مرتبط در فضای مشترک نزدیک شوند؛ CLIP مولد تصویر نیست.",
    architecture: "image encoder + text encoder + contrastive objective", input: "image/text pairs", output: "aligned embeddings",
    process: ["image encode", "text encode", "normalize", "similarity matrix", "contrastive loss/search"], repo: "https://github.com/openai/CLIP",
    paper: "https://arxiv.org/abs/2103.00020", license: "MIT", tags: ["contrastive", "retrieval", "embeddings"], parents: ["embedding"], exhibit: "multimodal",
  }),
  node({
    id: "llava", category: "multimodal", title: "LLaVA", subtitle: "Vision encoder متصل به LLM",
    summary: "ویژگی‌های image encoder با projector به فضای embedding مدل زبانی برده می‌شوند؛ LLM سپس tokenهای متن را با context تصویری تولید می‌کند.",
    architecture: "vision encoder + multimodal projector + autoregressive LLM", input: "image + prompt", output: "text tokens",
    process: ["vision patches", "vision encoder", "projector", "LLM context", "text decode"], repo: "https://github.com/haotian-liu/LLaVA",
    paper: "https://arxiv.org/abs/2304.08485", license: "Apache-2.0 برای کد؛ base model/weights شرایط جدا دارند.", tags: ["VLM", "projector", "vision"], parents: ["clip", "dense-transformer"], exhibit: "multimodal",
  }),
  node({
    id: "sam", category: "multimodal", title: "Segment Anything", subtitle: "Promptable image segmentation",
    summary: "Image encoder یک embedding قابل‌استفادهٔ مجدد می‌سازد؛ prompt encoder نقطه/جعبه/mask را encode و mask decoder خروجی segmentation می‌دهد.",
    architecture: "image encoder + prompt encoder + lightweight mask decoder", input: "image + points/boxes/mask prompt", output: "segmentation masks",
    process: ["image embedding", "prompt embedding", "mask decoder", "quality score", "mask"], repo: "https://github.com/facebookresearch/segment-anything",
    paper: "https://arxiv.org/abs/2304.02643", license: "Apache-2.0", tags: ["segmentation", "prompt", "vision"], exhibit: "multimodal",
  }),
  node({
    id: "multimodal-token-space", category: "multimodal", title: "پل چندوجهی", subtitle: "هر modality مسیر token/latent خودش را دارد",
    summary: "متن، patch تصویر، frame و audio code ذاتاً یکی نیستند. connector، resampler یا projector آن‌ها را به فضای قابل‌مصرف backbone نگاشت می‌کند.",
    architecture: "modality encoders + connector/resampler + shared backbone", input: "mixed modalities", output: "shared sequence/latent",
    process: ["modality preprocess", "specialized encoder", "alignment", "fusion/attention", "decoder/head"], repo: "https://github.com/huggingface/transformers",
    tags: ["fusion", "projector", "tokens"], parents: ["clip", "llava"], exhibit: "multimodal",
  }),

  node({
    id: "llama-cpp", category: "system", title: "llama.cpp", subtitle: "Inference محلی C/C++ روی CPU/GPU",
    summary: "llama.cpp وزن GGUF را memory-map می‌کند، kernelهای quantized و SIMD را اجرا، KV cache را نگهداری و tokenها را autoregressive تولید می‌کند.",
    architecture: "portable inference runtime over ggml tensors", input: "GGUF + prompt + sampling config", output: "tokens + timing metrics",
    process: ["open/mmap GGUF", "tokenize", "prefill", "layer kernels", "KV cache", "sample", "repeat"], repo: "https://github.com/ggml-org/llama.cpp",
    license: "MIT", params: "runtime؛ اندازه از GGUF می‌آید", compute: "CPU معمولاً memory-bandwidth bound است؛ SIMD، thread count و quantization تعیین‌کننده‌اند.", tags: ["CPU", "GGUF", "SIMD"], parents: ["quantization"], exhibit: "cpu",
  }),
  node({
    id: "quantization", category: "system", title: "GGUF و Quantization", subtitle: "کاهش بیت وزن برای حافظه/پهنای‌باند",
    summary: "Quantization وزن‌های float را به نمایش کم‌بیت می‌برد. حافظه و traffic کم می‌شود، اما خطای تقریب، kernel و کیفیت به scheme وابسته‌اند.",
    architecture: "file format + blockwise quantized tensor kernels", input: "checkpoint float", output: "GGUF quantized weights",
    process: ["convert tensors", "calibrate/imatrix optional", "block quantize", "write metadata", "runtime dequantize/matmul"], repo: "https://github.com/ggml-org/llama.cpp",
    license: "MIT", tags: ["Q4", "Q8", "memory", "GGUF"], parents: ["dense-transformer", "sparse-moe"], exhibit: "cpu",
  }),
  node({
    id: "transformers-ecosystem", category: "system", title: "Hugging Face Transformers", subtitle: "مدل، tokenizer، config و generation",
    summary: "کتابخانه‌ای برای بارگذاری معماری/وزن/پردازشگر و اجرای train/inference؛ خود کتابخانه یک مدل واحد نیست.",
    architecture: "model/config/tokenizer/generation abstraction layer", input: "model artifacts + tensors", output: "task outputs",
    process: ["resolve config", "instantiate architecture", "load weights", "preprocess", "forward/generate"], repo: "https://github.com/huggingface/transformers",
    license: "Apache-2.0؛ مجوز هر model جداست.", tags: ["ecosystem", "PyTorch", "generation"], parents: ["tokenizer", "dense-transformer"],
  }),
  node({
    id: "diffusers-ecosystem", category: "system", title: "Hugging Face Diffusers", subtitle: "Pipeline + model + scheduler",
    summary: "کتابخانهٔ modular برای diffusion/flow در تصویر، ویدئو و صدا؛ scheduler قابل‌تعویض است و pipeline اجزا را کنار هم می‌گذارد.",
    architecture: "pipeline orchestration around denoisers, schedulers and encoders", input: "components + conditions", output: "media samples",
    process: ["load components", "prepare scheduler", "condition", "denoise loop", "decode"], repo: "https://github.com/huggingface/diffusers",
    license: "Apache-2.0؛ مدل‌ها مجوز مستقل دارند.", tags: ["pipeline", "scheduler", "media"], parents: ["diffusion-core"], exhibit: "diffusion",
  }),
  node({
    id: "vllm", category: "system", title: "vLLM", subtitle: "Serving GPU با paged KV cache",
    summary: "موتور serving برای throughput/latency بالا و batching پیوسته؛ با runtime سبک CPU یکی نیست و عمدتاً برای شتاب‌دهنده‌ها طراحی شده است.",
    architecture: "LLM serving engine with paged attention and continuous batching", input: "requests + model", output: "streamed tokens",
    process: ["schedule requests", "batch prefill/decode", "paged KV", "kernels", "stream"], repo: "https://github.com/vllm-project/vllm",
    paper: "https://arxiv.org/abs/2309.06180", license: "Apache-2.0", tags: ["serving", "GPU", "batching"], parents: ["dense-transformer", "sparse-moe"],
  }),
  node({
    id: "onnx-runtime", category: "system", title: "ONNX Runtime", subtitle: "Graph optimization و execution providers",
    summary: "مدل به graph ONNX تبدیل و با provider مناسب CPU، DirectML، CUDA یا دیگر backendها اجرا می‌شود؛ همهٔ معماری‌ها/exportها یکسان پشتیبانی نمی‌شوند.",
    architecture: "portable graph runtime + hardware execution providers", input: "ONNX graph + tensors", output: "tensor outputs",
    process: ["load graph", "shape/type check", "graph optimize", "provider partition", "execute"], repo: "https://github.com/microsoft/onnxruntime",
    license: "MIT", tags: ["CPU", "DirectML", "graph"], parents: ["dense-transformer", "diffusion-core"],
  }),
  node({
    id: "faiss-rag", category: "system", title: "FAISS + RAG", subtitle: "بازیابی بیرون وزن مدل",
    summary: "FAISS بردارهای نزدیک را از index برمی‌گرداند؛ RAG متن سندهای منتخب را به context مولد می‌افزاید. retrieval top-k تعداد سند است، نه token.",
    architecture: "embedding retriever + vector index + generator", input: "query + corpus", output: "ranked passages + conditioned generation",
    process: ["embed query", "ANN search", "top-k passages", "prompt assembly", "generate with citations"], repo: "https://github.com/facebookresearch/faiss",
    paper: "https://arxiv.org/abs/2005.11401", license: "MIT برای FAISS؛ دادهٔ corpus مجوز مستقل دارد.", tags: ["RAG", "vector", "retrieval"], parents: ["embedding", "dense-transformer"],
  }),
  node({
    id: "agents-tools", category: "system", title: "Agents و Tool Use", subtitle: "مدل پیشنهاد می‌دهد، میزبان اجرا می‌کند",
    summary: "مدل می‌تواند call ساختاری تولید کند؛ application باید schema، مجوز، timeout، نتیجه و loop limit را کنترل کند. ابزار بخشی از وزن مدل نیست.",
    architecture: "model + policy + tool executor + state loop", input: "goal + state + allowed tools", output: "actions, observations and answer",
    process: ["plan/propose", "validate", "execute externally", "observe", "revise/finish"], repo: "https://github.com/openai/openai-agents-python",
    license: "MIT برای SDK؛ هر tool و اثر جانبی سیاست جدا می‌خواهد.", tags: ["tools", "orchestrator", "state"], parents: ["dense-transformer", "faiss-rag"],
  }),
  node({
    id: "agent-harness", category: "agentic", title: "Agent Harness", subtitle: "پوستهٔ کنترل اجرا پیرامون مدل",
    summary: "Harness مدل، context، state، ابزار، policy، approval، retry، بودجه و trace را در یک چرخهٔ قابل توقف کنار هم می‌گذارد. Harness یک استاندارد واحد نیست؛ یک لایهٔ مهندسی است.",
    architecture: "event-driven runtime + policy gates + tool adapters + state store", input: "هدف + مدل + policy + ابزارهای مجاز", output: "event stream + state + نتیجهٔ پایانی",
    process: ["ایجاد Run", "ساخت context", "تصمیم مدل", "گیت policy", "ابزار/مشاهده", "verify و stop"],
    repo: "https://github.com/openai/openai-agents-python", license: "MIT برای SDK نمونه؛ ابزار، داده و سرویس‌ها مجوز مستقل دارند.",
    tags: ["harness", "runtime", "policy", "events"], parents: ["agents-tools"], exhibit: "agentic",
  }),
  node({
    id: "context-engineering", category: "agentic", title: "Context Engineering", subtitle: "انتخاب، اعتماد، ترتیب و بودجهٔ ورودی",
    summary: "Context Engineering همهٔ دادهٔ قابل‌مشاهده در inference را مدیریت می‌کند: policy، هدف، history، RAG، حافظه، schema ابزار و observation؛ انباشتن متن بیشتر الزاماً بهتر نیست.",
    architecture: "provenance-aware context compiler + retrieval + compaction + token budget", input: "منابع context با trust و priority", output: "manifest + بستهٔ ورودی محدود",
    process: ["برچسب‌گذاری منشأ", "فیلتر اعتماد", "رتبه‌بندی", "حذف تکرار", "بودجه‌بندی", "ثبت حذف/فشرده‌سازی"],
    repo: "https://github.com/langchain-ai/langgraph", paper: "https://arxiv.org/abs/2307.03172",
    license: "MIT برای LangGraph؛ دادهٔ بازیابی و حافظه سیاست مستقل می‌خواهد.", tags: ["context", "memory", "RAG", "compaction"], parents: ["faiss-rag", "agent-harness"], exhibit: "agentic",
  }),
  node({
    id: "orchestration-patterns", category: "agentic", title: "الگوهای Orchestration", subtitle: "Chain، Router، Fan-out، Supervisor و Handoff",
    summary: "Orchestration مالکیت task، وابستگی، parallelism، join و توقف را تعیین می‌کند. انتخاب توپولوژی باید رفتار event و state را تغییر دهد، نه فقط شکل نمودار را.",
    architecture: "typed task graph + scheduler + ownership + join conditions", input: "هدف + task graph + registry عامل‌ها", output: "نتایج شاخه‌ها + synthesis قابل ردیابی",
    process: ["تقسیم task", "انتخاب مالک", "dispatch", "checkpoint", "join", "verify"],
    repo: "https://github.com/langchain-ai/langgraph", license: "MIT؛ الگو مفهومی است و فریم‌ورک تضمین صحت نمی‌دهد.",
    tags: ["supervisor", "handoff", "fan-out", "DAG"], parents: ["agent-harness"], exhibit: "agentic",
  }),
  node({
    id: "mcp-protocol", category: "agentic", title: "MCP", subtitle: "اتصال Host به Context و Tool Server",
    summary: "MCP 2026-07-28 با JSON-RPC ابزار، منبع و prompt را قرارداد می‌کند و core آن بی‌حالت است؛ هر درخواست نسخه/capability خود را دارد. Host مسئول رضایت، authorization، جداسازی serverها و policy می‌ماند.",
    architecture: "stateless client-host-server protocol with per-request capabilities", input: "JSON-RPC self-contained + نسخه و capability", output: "resources، prompts، tools و results",
    process: ["تثبیت نسخه", "server/discover اختیاری", "کشف primitive", "call/read", "اعتبارسنجی و trace"],
    repo: "https://github.com/modelcontextprotocol/modelcontextprotocol", license: "مشخصات باز؛ ادعای conformance نیازمند نسخه و آزمون سازگاری است.",
    tags: ["MCP", "JSON-RPC", "tools", "resources"], parents: ["agent-harness", "context-engineering"], exhibit: "agentic",
  }),
  node({
    id: "a2a-protocol", category: "agentic", title: "A2A", subtitle: "ارتباط افقی عامل‌های مستقل",
    summary: "A2A کشف قابلیت، Message، Task، Artifact و وضعیت کار طولانی را میان عامل‌های مستقل مبادله می‌کند. با MCP نقش یکسان ندارد و جزئیات داخلی عامل می‌تواند opaque بماند.",
    architecture: "Agent Card + task lifecycle + message/artifact exchange", input: "Agent Card + Message/Task", output: "status، event و Artifact",
    process: ["کشف Agent Card", "authentication", "ارسال task", "stream status", "دریافت artifact"],
    repo: "https://github.com/a2aproject/A2A", license: "Apache-2.0 برای پروژه؛ سازگاری باید به نسخه و TCK مقید شود.",
    tags: ["A2A", "agent-to-agent", "task", "artifact"], parents: ["orchestration-patterns"], exhibit: "agentic",
  }),
  node({
    id: "agent-observability", category: "agentic", title: "Trace، Evals و Replay", subtitle: "رویداد قابل مشاهده، نه ذهن پنهان",
    summary: "model call، tool call، handoff، policy و checkpoint به span و event تبدیل می‌شوند. این trace داده و تصمیم ثبت‌شده را نشان می‌دهد؛ زنجیرهٔ خصوصی فکر مدل را آشکار نمی‌کند.",
    architecture: "event log + W3C trace context + GenAI semantic attributes + eval gates", input: "رویداد runtime و معیار", output: "trace، metric، replay و نتیجهٔ eval",
    process: ["trace root", "spanهای فرزند", "redaction", "metric aggregation", "replay", "release gate"],
    repo: "https://github.com/open-telemetry/semantic-conventions-genai", license: "Apache-2.0؛ قراردادهای GenAI Agent در وضعیت Development هستند.",
    tags: ["OpenTelemetry", "trace", "eval", "replay"], parents: ["agent-harness", "orchestration-patterns"], exhibit: "agentic",
  }),
]);

export const CATALOG_BY_ID = new Map(MODEL_CATALOG.map((item) => [item.id, item]));

export const RELATIONS = Object.freeze(
  MODEL_CATALOG.flatMap((item) => item.parents.map((parent) => Object.freeze({
    id: `${parent}--${item.id}`,
    from: parent,
    to: item.id,
    relation: "influences_or_composes",
  }))),
);

export const TOUR_STOPS = Object.freeze([
  { id: "data-lifecycle", title: "داده پیش از مدل", body: "هر توانایی از داده، هدف آموزش و محدودیت ارزیابی آغاز می‌شود. منبع و مجوز داده بخشی از معماری عملی سامانه‌اند." },
  { id: "dense-transformer", title: "Transformer چگال", body: "Attention ارتباط tokenها و MLP تبدیل ویژگی را انجام می‌دهد. در مدل چگال تقریباً همهٔ وزن‌ها در هر token فعال‌اند." },
  { id: "sparse-moe", title: "MoE و تفاوت وزن کل/فعال", body: "Router فقط expertهای محدودی را برای هر token فعال می‌کند، اما حافظه هنوز باید expertهای کل مدل را نگه دارد." },
  { id: "deepseek-r1", title: "DeepSeek-R1 زیر میکروسکوپ", body: "R1 یک مدل ۶۷۱B مبتنی بر V3 است. post-training reasoning با کوچک‌شدن معماری یا CPU-friendly شدن یکی نیست." },
  { id: "deepseek-r1-distill", title: "راه عملی‌تر CPU", body: "نسخه‌های Distill dense کوچک‌ترند. با GGUF و quantization می‌توان آن‌ها را در llama.cpp روی CPU اجرا کرد." },
  { id: "latent-diffusion", title: "تصویر: نویز تا latent", body: "در latent diffusion، denoiser بارها latent نویزی را اصلاح و VAE در پایان آن را به pixel تبدیل می‌کند." },
  { id: "video-dit", title: "ویدئو: فضا به‌علاوهٔ زمان", body: "مدل ویدئو باید چند frame را هم‌زمان سازگار کند؛ latent زمانی و attention فضازمانی هزینه را بالا می‌برند." },
  { id: "audiocraft", title: "صدا: tokenهای codec", body: "برخی مدل‌های صوتی ابتدا audio را به codeهای گسسته می‌برند، LM آن‌ها را تولید و codec دوباره waveform می‌سازد." },
  { id: "code-agent-loop", title: "کد: مدل به‌علاوهٔ ابزار", body: "تولید code token با اجرای امن، بررسی AST و تست متفاوت است. میزبان مسئول sandbox و مجوز است." },
  { id: "faiss-rag", title: "دانش بیرون وزن", body: "RAG اسناد را بازیابی و وارد context می‌کند. این دانش در همان لحظه به وزن مدل تبدیل نمی‌شود." },
  { id: "agents-tools", title: "عامل: حلقهٔ کنترل", body: "مدل action پیشنهاد می‌دهد؛ policy آن را می‌سنجد، میزبان اجرا می‌کند و observation برای گام بعد بازمی‌گردد." },
  { id: "agent-harness", title: "Harness: پوستهٔ اجرای عامل", body: "Harness همان کنترل‌گر اطراف مدل است: state، ابزار، مجوز، بودجه، retry، checkpoint و trace را مدیریت می‌کند." },
  { id: "context-engineering", title: "Context: انتخاب آگاهانه", body: "Context فقط prompt نیست؛ policy، هدف، RAG، حافظه و نتیجهٔ ابزار با منشأ، اعتماد و سقف token انتخاب و مرتب می‌شوند." },
  { id: "orchestration-patterns", title: "Orchestration: مالکیت و هماهنگی", body: "Chain، router، fan-out، supervisor و handoff هزینه و failure mode متفاوت دارند؛ شبیه‌ساز این تفاوت را در eventها نشان می‌دهد." },
  { id: "agent-observability", title: "Trace و ارزیابی", body: "رویدادها و spanها امکان replay و ممیزی می‌دهند؛ آنچه دیده می‌شود state و تصمیم ثبت‌شده است، نه زنجیرهٔ پنهان فکر مدل." },
  { id: "diffusers-ecosystem", title: "مرز نهایی", body: "وجود یک کارت یا شبیه‌سازی سه‌بعدی اثبات اجرای checkpoint نیست. این برنامه معماری را توضیح می‌دهد و اجرای واقعی را جدا برچسب می‌زند." },
]);

export const CPU_MODELS = Object.freeze([
  { id: "r1-1.5b", label: "R1 Distill Qwen 1.5B", totalB: 1.5, activeB: 1.5, kvBytesPerToken: 28672, caveat: "dense student؛ معماری 671B MoE نیست" },
  { id: "r1-7b", label: "R1 Distill Qwen 7B", totalB: 7, activeB: 7, kvBytesPerToken: 57344, caveat: "اجرای CPU عملی‌تر با Q4/Q5 و RAM کافی" },
  { id: "r1-14b", label: "R1 Distill Qwen 14B", totalB: 14, activeB: 14, kvBytesPerToken: 196608, caveat: "dense؛ context بلند KV cache را بزرگ می‌کند" },
  { id: "r1-32b", label: "R1 Distill Qwen 32B", totalB: 32, activeB: 32, kvBytesPerToken: 262144, caveat: "RAM و پهنای‌باند بالا لازم است" },
  { id: "r1-70b", label: "R1 Distill Llama 70B", totalB: 70, activeB: 70, kvBytesPerToken: 327680, caveat: "روی CPU مصرف‌کننده کند و پرحافظه است" },
  { id: "r1-671b", label: "DeepSeek-R1 Full 671B MoE", totalB: 671, activeB: 37, kvBytesPerToken: 262144, caveat: "همهٔ وزن expertها باید ذخیره شوند؛ estimator سرعت برای MoE خوش‌بینانه است" },
]);

export const OPEN_SOURCE_STACK = Object.freeze([
  { name: "Electron", version: "44.0.0", repo: "https://github.com/electron/electron", license: "MIT" },
  { name: "Three.js", version: "0.185.1", repo: "https://github.com/mrdoob/three.js", license: "MIT" },
  { name: "Vite", version: "8.2.2", repo: "https://github.com/vitejs/vite", license: "MIT" },
  { name: "electron-builder", version: "26.15.3", repo: "https://github.com/electron-userland/electron-builder", license: "MIT" },
  { name: "Fontsource", version: "5.3.0", repo: "https://github.com/fontsource/fontsource", license: "MIT / OFL fonts" },
]);
